### ISSUE TITLE
Installation fails in node.js 0.12 due to execSync module dependency

### ISSUE THREAD

**Issue by nablaa** [mraxus/ds18x20.js#2]
ds18x20 cannot be currently installed with node.js 0.12 as execSync module doesn't work with nodejs 0.12 and the author of that module cannot make an update to the module to fix that:
https://github.com/mgutz/execSync/issues/38

This could be fixed by, for example, using [sync-exec](https://www.npmjs.com/package/sync-exec) module instead.

**Comment by mraxus** [comment]
Thanks for the fix =)

**Comment by Svendle** [comment]
It looks like the fix to this has not been deployed to npm, so you can't npm install the package anymore.

**Comment by mraxus** [comment]
Sorry for that. It should be up as v 0.2.0. Hope it works!
